cnf(i_0_1,plain,(lowairspace(X1)|uppairspace(X1))).
cnf(i_0_12,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~uppairspace(esk1_0)|~uppairspace(esk2_0))).
cnf(i_0_8,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~uppairspace(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_10,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~uppairspace(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_13,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~uppairspace(esk1_0)|~uppairspace(esk2_0))).
cnf(i_0_9,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~uppairspace(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_11,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~uppairspace(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_6,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~uppairspace(esk1_0)|~uppairspace(esk2_0))).
cnf(i_0_2,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~uppairspace(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_4,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~uppairspace(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_7,negated_conjecture,(military(esk1_0)|military(esk2_0)|~uppairspace(esk1_0)|~uppairspace(esk2_0))).
cnf(i_0_3,negated_conjecture,(military(esk1_0)|military(esk2_0)|~uppairspace(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_5,negated_conjecture,(military(esk1_0)|military(esk2_0)|~uppairspace(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_36,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~a_d_app(esk1_0))).
cnf(i_0_24,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_32,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_34,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_20,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_22,negated_conjecture,(milregion(esk1_0)|milregion(esk2_0)|~lowairspace(esk1_0)|~dub_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_37,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~a_d_app(esk1_0))).
cnf(i_0_25,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_33,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_35,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_21,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_23,negated_conjecture,(milregion(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~dub_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_30,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~a_d_app(esk1_0))).
cnf(i_0_18,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_26,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_28,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_14,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~lowairspace(esk1_0)|~a_d_app(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_16,negated_conjecture,(milregion(esk2_0)|military(esk1_0)|~lowairspace(esk1_0)|~dub_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_31,negated_conjecture,(military(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~a_d_app(esk1_0))).
cnf(i_0_19,negated_conjecture,(military(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~uppairspace(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_27,negated_conjecture,(military(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~a_d_app(esk2_0))).
cnf(i_0_29,negated_conjecture,(military(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_15,negated_conjecture,(military(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~a_d_app(esk2_0)|~dub_app(esk1_0))).
cnf(i_0_17,negated_conjecture,(military(esk1_0)|military(esk2_0)|~lowairspace(esk1_0)|~dub_app(esk1_0)|~dub_app(esk2_0))).
cnf(i_0_44,negated_conjecture,(lowairspace(X2)|uppairspace(X2)|uppairspace(X1)|a_d_app(X1)|dub_app(X1))).
cnf(i_0_39,negated_conjecture,(lowairspace(X2)|uppairspace(X2)|~milregion(X1)|~military(X1))).
cnf(i_0_46,negated_conjecture,(lowairspace(X2)|uppairspace(X2)|uppairspace(X1)|a_d_app(X2)|a_d_app(X1)|dub_app(X1))).
cnf(i_0_45,negated_conjecture,(lowairspace(X2)|uppairspace(X2)|uppairspace(X1)|a_d_app(X1)|dub_app(X2)|dub_app(X1))).
cnf(i_0_47,negated_conjecture,(uppairspace(X2)|uppairspace(X1)|a_d_app(X2)|a_d_app(X1)|dub_app(X2)|dub_app(X1))).
cnf(i_0_41,negated_conjecture,(lowairspace(X2)|uppairspace(X2)|a_d_app(X2)|~milregion(X1)|~military(X1))).
cnf(i_0_40,negated_conjecture,(lowairspace(X2)|uppairspace(X2)|dub_app(X2)|~milregion(X1)|~military(X1))).
cnf(i_0_42,negated_conjecture,(uppairspace(X2)|a_d_app(X2)|dub_app(X2)|~milregion(X1)|~military(X1))).
cnf(i_0_43,negated_conjecture,(uppairspace(X1)|a_d_app(X1)|dub_app(X1)|~milregion(X2)|~military(X2))).
cnf(i_0_38,negated_conjecture,(~milregion(X2)|~milregion(X1)|~military(X2)|~military(X1))).
