%------------------------------------------------------------------------------
% File     : COM154^1 : TPTP v7.5.0. Released v7.0.0.
% Domain   : Computing Theory
% Problem  : Abstract completeness 131
% Version  : [Bla16] axioms : Especial.
% English  :

% Refs     : [BPT14] Blanchette et al. (2014), Abstract Completeness
%          : [RB15]  Reynolds & Blanchette (2015), A Decision Procedure for
%          : [Bla16] Blanchette (2016), Email to Geoff Sutcliffe
% Source   : [Bla16]
% Names    : abstract_completeness__131.p [Bla16]

% Status   : Theorem
% Rating   : 1.00 v7.5.0, 0.33 v7.2.0, 0.50 v7.1.0
% Syntax   : Number of formulae    :  373 (   0 unit;  71 type;   0 defn)
%            Number of atoms       : 3487 ( 257 equality;1798 variable)
%            Maximal formula depth :   17 (   8 average)
%            Number of connectives : 2912 ( 108   ~;   9   |;  26   &;2479   @)
%                                         (   0 <=>; 290  =>;   0  <=;   0 <~>)
%                                         (   0  ~|;   0  ~&)
%            Number of type conns  :  181 ( 181   >;   0   *;   0   +;   0  <<)
%            Number of symbols     :   75 (  71   :;   0   =;   0  @=)
%                                         (   0  !!;   0  ??;   0 @@+;   0 @@-)
%            Number of variables   :  823 (   7 sgn; 688   !;  22   ?;  53   ^)
%                                         ( 823   :;  60  !>;   0  ?*)
%                                         (   0  @-;   0  @+)
% SPC      : TH1_THM_EQU_NAR

% Comments : This file was generated by Isabelle (most likely Sledgehammer)
%            2016-07-13 14:53:38.952
%------------------------------------------------------------------------------
%----Could-be-implicit typings (6)
thf(ty_t_Stream_Ostream,type,(
    stream: $tType > $tType )).

thf(ty_t_List_Olist,type,(
    list: $tType > $tType )).

thf(ty_t_Set_Oset,type,(
    set: $tType > $tType )).

thf(ty_t_Nat_Onat,type,(
    nat: $tType )).

thf(ty_t_itself,type,(
    itself: $tType > $tType )).

thf(ty_tf_rule,type,(
    rule: $tType )).

%----Explicit typings (65)
thf(sy_cl_Finite__Set_Ofinite,type,(
    finite_finite: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_HOL_Otype,type,(
    type: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Oone,type,(
    one: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Ozero,type,(
    zero: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Ominus,type,(
    minus: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Obot,type,(
    bot: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Oord,type,(
    ord: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Num_Oneg__numeral,type,(
    neg_numeral: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Oorder,type,(
    order: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Ogroup__add,type,(
    group_add: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Ono__bot,type,(
    no_bot: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Ono__top,type,(
    no_top: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Transcendental_Oln,type,(
    ln: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Olinorder,type,(
    linorder: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Opreorder,type,(
    preorder: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Rings_Ozero__neq__one,type,(
    zero_neq_one: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Countable_Ocountable,type,(
    countable: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Oorder__bot,type,(
    order_bot: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Owellorder,type,(
    wellorder: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Rings_Ozero__less__one,type,(
    zero_less_one: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Orderings_Odense__order,type,(
    dense_order: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Rings_Olinordered__idom,type,(
    linordered_idom: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Ocomm__monoid__diff,type,(
    comm_monoid_diff: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Rings_Olinordered__semidom,type,(
    linordered_semidom: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Oordered__ab__group__add,type,(
    ordered_ab_group_add: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Ocancel__comm__monoid__add,type,(
    cancel1352612707id_add: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Ocancel__ab__semigroup__add,type,(
    cancel146912293up_add: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Rings_Olinordered__nonzero__semiring,type,(
    linord1659791738miring: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_cl_Groups_Ocanonically__ordered__monoid__add,type,(
    canoni770627133id_add: 
      !>[A: $tType] :
        ( ( itself @ A ) > $o ) )).

thf(sy_c_Abstract__Completeness__Mirabelle__wdxnrclvrt_ORuleSystem__Defs_Ofenum,type,(
    abstra1774373515_fenum: 
      !>[Rule: $tType] :
        ( ( stream @ Rule ) > ( stream @ Rule ) ) )).

thf(sy_c_Countable__Set_Ocountable,type,(
    countable_countable: 
      !>[A: $tType] :
        ( ( set @ A ) > $o ) )).

thf(sy_c_Groups_Ominus__class_Ominus,type,(
    minus_minus: 
      !>[A: $tType] :
        ( A > A > A ) )).

thf(sy_c_Groups_Oone__class_Oone,type,(
    one_one: 
      !>[A: $tType] : A )).

thf(sy_c_Groups_Ozero__class_Ozero,type,(
    zero_zero: 
      !>[A: $tType] : A )).

thf(sy_c_If,type,(
    if: 
      !>[A: $tType] :
        ( $o > A > A > A ) )).

thf(sy_c_List_Oappend,type,(
    append: 
      !>[A: $tType] :
        ( ( list @ A ) > ( list @ A ) > ( list @ A ) ) )).

thf(sy_c_List_Olist_Omap,type,(
    map: 
      !>[A: $tType,Aa: $tType] :
        ( ( A > Aa ) > ( list @ A ) > ( list @ Aa ) ) )).

thf(sy_c_List_Omap__tailrec,type,(
    map_tailrec: 
      !>[A: $tType,B: $tType] :
        ( ( A > B ) > ( list @ A ) > ( list @ B ) ) )).

thf(sy_c_Nat_OSuc,type,(
    suc: nat > nat )).

thf(sy_c_Nat_Onat_Ocase__nat,type,(
    case_nat: 
      !>[A: $tType] :
        ( A > ( nat > A ) > nat > A ) )).

thf(sy_c_Nat_Onat_Opred,type,(
    pred: nat > nat )).

thf(sy_c_Num_Oneg__numeral__class_Odbl__inc,type,(
    neg_numeral_dbl_inc: 
      !>[A: $tType] :
        ( A > A ) )).

thf(sy_c_Orderings_Obot__class_Obot,type,(
    bot_bot: 
      !>[A: $tType] : A )).

thf(sy_c_Orderings_Oord__class_Oless,type,(
    ord_less: 
      !>[A: $tType] :
        ( A > A > $o ) )).

thf(sy_c_Pure_Otype,type,(
    type2: 
      !>[A: $tType] :
        ( itself @ A ) )).

thf(sy_c_Set_OBex,type,(
    bex: 
      !>[A: $tType] :
        ( ( set @ A ) > ( A > $o ) > $o ) )).

thf(sy_c_Set_OCollect,type,(
    collect: 
      !>[A: $tType] :
        ( ( A > $o ) > ( set @ A ) ) )).

thf(sy_c_Set_Ois__empty,type,(
    is_empty: 
      !>[A: $tType] :
        ( ( set @ A ) > $o ) )).

thf(sy_c_Stream_Oflat,type,(
    flat: 
      !>[A: $tType] :
        ( ( stream @ ( list @ A ) ) > ( stream @ A ) ) )).

thf(sy_c_Stream_Oshift,type,(
    shift: 
      !>[A: $tType] :
        ( ( list @ A ) > ( stream @ A ) > ( stream @ A ) ) )).

thf(sy_c_Stream_Ositerate,type,(
    siterate: 
      !>[A: $tType] :
        ( ( A > A ) > A > ( stream @ A ) ) )).

thf(sy_c_Stream_Osmerge,type,(
    smerge: 
      !>[A: $tType] :
        ( ( stream @ ( stream @ A ) ) > ( stream @ A ) ) )).

thf(sy_c_Stream_Osnth,type,(
    snth: 
      !>[A: $tType] :
        ( ( stream @ A ) > nat > A ) )).

thf(sy_c_Stream_Ostake,type,(
    stake: 
      !>[A: $tType] :
        ( nat > ( stream @ A ) > ( list @ A ) ) )).

thf(sy_c_Stream_Ostream_Osmap,type,(
    smap: 
      !>[A: $tType,Aa: $tType] :
        ( ( A > Aa ) > ( stream @ A ) > ( stream @ Aa ) ) )).

thf(sy_c_Stream_Ostream_Osset,type,(
    sset: 
      !>[A: $tType] :
        ( ( stream @ A ) > ( set @ A ) ) )).

thf(sy_c_Transcendental_Oln__class_Oln,type,(
    ln_ln: 
      !>[A: $tType] :
        ( A > A ) )).

thf(sy_c_Transcendental_Opowr,type,(
    powr: 
      !>[A: $tType] :
        ( A > A > A ) )).

thf(sy_c_member,type,(
    member: 
      !>[A: $tType] :
        ( A > ( set @ A ) > $o ) )).

thf(sy_v_m____,type,(
    m: nat )).

thf(sy_v_n____,type,(
    n: nat )).

thf(sy_v_na____,type,(
    na: nat )).

thf(sy_v_r____,type,(
    r: rule )).

thf(sy_v_rsa____,type,(
    rsa: ( list @ rule ) )).

thf(sy_v_rules,type,(
    rules: ( stream @ rule ) )).

%----Relevant facts (252)
thf(fact_0__092_060open_0620_A_060_An_____092_060close_062,axiom,
    ( ord_less @ nat @ ( zero_zero @ nat ) @ n )).

% \<open>0 < n__\<close>
thf(fact_1_r,axiom,
    ( r
    = ( snth @ rule @ rules @ m ) )).

% r
thf(fact_2_local_Oalw,axiom,
    ( ord_less @ nat @ ( zero_zero @ nat ) @ na )).

% local.alw
thf(fact_3__092_060open_062r_A_092_060in_062_AR_092_060close_062,axiom,
    ( member @ rule @ r @ ( sset @ rule @ rules ) )).

% \<open>r \<in> R\<close>
thf(fact_4__092_060open_062_092_060And_062thesis_O_A_I_092_060And_062m_O_Ar_A_061_Arules_A_B_B_Am_A_092_060Longrightarrow_062_Athesis_J_A_092_060Longrightarrow_062_Athesis_092_060close_062,axiom,(
    ~ ( ! [M: nat] :
          ( r
         != ( snth @ rule @ rules @ M ) ) ) )).

% \<open>\<And>thesis. (\<And>m. r = rules !! m \<Longrightarrow> thesis) \<Longrightarrow> thesis\<close>
thf(fact_5_sset__fenum,axiom,
    ( ( sset @ rule @ ( abstra1774373515_fenum @ rule @ rules ) )
    = ( sset @ rule @ rules ) )).

% sset_fenum
thf(fact_6_fenum__def,axiom,
    ( ( abstra1774373515_fenum @ rule @ rules )
    = ( flat @ rule
      @ ( smap @ nat @ ( list @ rule )
        @ ^ [N: nat] :
            ( stake @ rule @ N @ rules )
        @ ( siterate @ nat @ suc @ ( one_one @ nat ) ) ) ) )).

% fenum_def
thf(fact_7_shift__left__inj,axiom,(
    ! [A: $tType,Xs: ( list @ A ),S1: ( stream @ A ),S2: ( stream @ A )] :
      ( ( ( shift @ A @ Xs @ S1 )
        = ( shift @ A @ Xs @ S2 ) )
      = ( S1 = S2 ) ) )).

% shift_left_inj
thf(fact_8_NE__R,axiom,(
    ( sset @ rule @ rules )
 != ( bot_bot @ ( set @ rule ) ) )).

% NE_R
thf(fact_9_nat_Oinject,axiom,(
    ! [X2: nat,Y2: nat] :
      ( ( ( suc @ X2 )
        = ( suc @ Y2 ) )
      = ( X2 = Y2 ) ) )).

% nat.inject
thf(fact_10_old_Onat_Oinject,axiom,(
    ! [Nat: nat,Nat2: nat] :
      ( ( ( suc @ Nat )
        = ( suc @ Nat2 ) )
      = ( Nat = Nat2 ) ) )).

% old.nat.inject
thf(fact_11_smap__siterate,axiom,(
    ! [A: $tType,F: ( A > A ),X: A] :
      ( ( smap @ A @ A @ F @ ( siterate @ A @ F @ X ) )
      = ( siterate @ A @ F @ ( F @ X ) ) ) )).

% smap_siterate
thf(fact_12_stream_Omap__cong,axiom,(
    ! [B: $tType,A: $tType,X: ( stream @ A ),Ya: ( stream @ A ),F: ( A > B ),G: ( A > B )] :
      ( ( X = Ya )
     => ( ! [Z: A] :
            ( ( member @ A @ Z @ ( sset @ A @ Ya ) )
           => ( ( F @ Z )
              = ( G @ Z ) ) )
       => ( ( smap @ A @ B @ F @ X )
          = ( smap @ A @ B @ G @ Ya ) ) ) ) )).

% stream.map_cong
thf(fact_13_stream_Omap__cong0,axiom,(
    ! [B: $tType,A: $tType,X: ( stream @ A ),F: ( A > B ),G: ( A > B )] :
      ( ! [Z: A] :
          ( ( member @ A @ Z @ ( sset @ A @ X ) )
         => ( ( F @ Z )
            = ( G @ Z ) ) )
     => ( ( smap @ A @ B @ F @ X )
        = ( smap @ A @ B @ G @ X ) ) ) )).

% stream.map_cong0
thf(fact_14_stream_Oinj__map__strong,axiom,(
    ! [B: $tType,A: $tType,X: ( stream @ A ),Xa: ( stream @ A ),F: ( A > B ),Fa: ( A > B )] :
      ( ! [Z: A,Za: A] :
          ( ( member @ A @ Z @ ( sset @ A @ X ) )
         => ( ( member @ A @ Za @ ( sset @ A @ Xa ) )
           => ( ( ( F @ Z )
                = ( Fa @ Za ) )
             => ( Z = Za ) ) ) )
     => ( ( ( smap @ A @ B @ F @ X )
          = ( smap @ A @ B @ Fa @ Xa ) )
       => ( X = Xa ) ) ) )).

% stream.inj_map_strong
thf(fact_15_countable__R,axiom,
    ( countable_countable @ rule @ ( sset @ rule @ rules ) )).

% countable_R
thf(fact_16_RuleSystem__Defs_Ofenum__def,axiom,(
    ! [Rule: $tType] :
      ( ( abstra1774373515_fenum @ Rule )
      = ( ^ [Rules: ( stream @ Rule )] :
            ( flat @ Rule
            @ ( smap @ nat @ ( list @ Rule )
              @ ^ [N: nat] :
                  ( stake @ Rule @ N @ Rules )
              @ ( siterate @ nat @ suc @ ( one_one @ nat ) ) ) ) ) ) )).

% RuleSystem_Defs.fenum_def
thf(fact_17_neq0__conv,axiom,(
    ! [N2: nat] :
      ( ( N2
       != ( zero_zero @ nat ) )
      = ( ord_less @ nat @ ( zero_zero @ nat ) @ N2 ) ) )).

% neq0_conv
thf(fact_18_Suc__less__eq,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ ( suc @ M2 ) @ ( suc @ N2 ) )
      = ( ord_less @ nat @ M2 @ N2 ) ) )).

% Suc_less_eq
thf(fact_19_Suc__mono,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ M2 @ N2 )
     => ( ord_less @ nat @ ( suc @ M2 ) @ ( suc @ N2 ) ) ) )).

% Suc_mono
thf(fact_20_lessI,axiom,(
    ! [N2: nat] :
      ( ord_less @ nat @ N2 @ ( suc @ N2 ) ) )).

% lessI
thf(fact_21_snth__smap,axiom,(
    ! [A: $tType,B: $tType,F: ( B > A ),S: ( stream @ B ),N2: nat] :
      ( ( snth @ A @ ( smap @ B @ A @ F @ S ) @ N2 )
      = ( F @ ( snth @ B @ S @ N2 ) ) ) )).

% snth_smap
thf(fact_22_zero__less__Suc,axiom,(
    ! [N2: nat] :
      ( ord_less @ nat @ ( zero_zero @ nat ) @ ( suc @ N2 ) ) )).

% zero_less_Suc
thf(fact_23_less__Suc0,axiom,(
    ! [N2: nat] :
      ( ( ord_less @ nat @ N2 @ ( suc @ ( zero_zero @ nat ) ) )
      = ( N2
        = ( zero_zero @ nat ) ) ) )).

% less_Suc0
thf(fact_24_less__one,axiom,(
    ! [N2: nat] :
      ( ( ord_less @ nat @ N2 @ ( one_one @ nat ) )
      = ( N2
        = ( zero_zero @ nat ) ) ) )).

% less_one
thf(fact_25_gr0I,axiom,(
    ! [N2: nat] :
      ( ( N2
       != ( zero_zero @ nat ) )
     => ( ord_less @ nat @ ( zero_zero @ nat ) @ N2 ) ) )).

% gr0I
thf(fact_26_not__gr0,axiom,(
    ! [N2: nat] :
      ( ( ~ ( ord_less @ nat @ ( zero_zero @ nat ) @ N2 ) )
      = ( N2
        = ( zero_zero @ nat ) ) ) )).

% not_gr0
thf(fact_27_not__less0,axiom,(
    ! [N2: nat] :
      ~ ( ord_less @ nat @ N2 @ ( zero_zero @ nat ) ) )).

% not_less0
thf(fact_28_less__zeroE,axiom,(
    ! [N2: nat] :
      ~ ( ord_less @ nat @ N2 @ ( zero_zero @ nat ) ) )).

% less_zeroE
thf(fact_29_nat__neq__iff,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( M2 != N2 )
      = ( ( ord_less @ nat @ M2 @ N2 )
        | ( ord_less @ nat @ N2 @ M2 ) ) ) )).

% nat_neq_iff
thf(fact_30_less__not__refl,axiom,(
    ! [N2: nat] :
      ~ ( ord_less @ nat @ N2 @ N2 ) )).

% less_not_refl
thf(fact_31_less__not__refl2,axiom,(
    ! [N2: nat,M2: nat] :
      ( ( ord_less @ nat @ N2 @ M2 )
     => ( M2 != N2 ) ) )).

% less_not_refl2
thf(fact_32_less__not__refl3,axiom,(
    ! [S: nat,T: nat] :
      ( ( ord_less @ nat @ S @ T )
     => ( S != T ) ) )).

% less_not_refl3
thf(fact_33_measure__induct,axiom,(
    ! [A: $tType,F: ( A > nat ),P: ( A > $o ),A2: A] :
      ( ! [X3: A] :
          ( ! [Y: A] :
              ( ( ord_less @ nat @ ( F @ Y ) @ ( F @ X3 ) )
             => ( P @ Y ) )
         => ( P @ X3 ) )
     => ( P @ A2 ) ) )).

% measure_induct
thf(fact_34_gr__implies__not0,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ M2 @ N2 )
     => ( N2
       != ( zero_zero @ nat ) ) ) )).

% gr_implies_not0
thf(fact_35_less__irrefl__nat,axiom,(
    ! [N2: nat] :
      ~ ( ord_less @ nat @ N2 @ N2 ) )).

% less_irrefl_nat
thf(fact_36_nat__less__induct,axiom,(
    ! [P: ( nat > $o ),N2: nat] :
      ( ! [N3: nat] :
          ( ! [M3: nat] :
              ( ( ord_less @ nat @ M3 @ N3 )
             => ( P @ M3 ) )
         => ( P @ N3 ) )
     => ( P @ N2 ) ) )).

% nat_less_induct
thf(fact_37_infinite__descent,axiom,(
    ! [P: ( nat > $o ),N2: nat] :
      ( ! [N3: nat] :
          ( ~ ( P @ N3 )
         => ? [M3: nat] :
              ( ( ord_less @ nat @ M3 @ N3 )
              & ~ ( P @ M3 ) ) )
     => ( P @ N2 ) ) )).

% infinite_descent
thf(fact_38_infinite__descent0,axiom,(
    ! [P: ( nat > $o ),N2: nat] :
      ( ( P @ ( zero_zero @ nat ) )
     => ( ! [N3: nat] :
            ( ( ord_less @ nat @ ( zero_zero @ nat ) @ N3 )
           => ( ~ ( P @ N3 )
             => ? [M3: nat] :
                  ( ( ord_less @ nat @ M3 @ N3 )
                  & ~ ( P @ M3 ) ) ) )
       => ( P @ N2 ) ) ) )).

% infinite_descent0
thf(fact_39_linorder__neqE__nat,axiom,(
    ! [X: nat,Y3: nat] :
      ( ( X != Y3 )
     => ( ~ ( ord_less @ nat @ X @ Y3 )
       => ( ord_less @ nat @ Y3 @ X ) ) ) )).

% linorder_neqE_nat
thf(fact_40_less__nat__zero__code,axiom,(
    ! [N2: nat] :
      ~ ( ord_less @ nat @ N2 @ ( zero_zero @ nat ) ) )).

% less_nat_zero_code
thf(fact_41_measure__induct__rule,axiom,(
    ! [A: $tType,F: ( A > nat ),P: ( A > $o ),A2: A] :
      ( ! [X3: A] :
          ( ! [Y: A] :
              ( ( ord_less @ nat @ ( F @ Y ) @ ( F @ X3 ) )
             => ( P @ Y ) )
         => ( P @ X3 ) )
     => ( P @ A2 ) ) )).

% measure_induct_rule
thf(fact_42_infinite__descent__measure,axiom,(
    ! [A: $tType,P: ( A > $o ),V: ( A > nat ),X: A] :
      ( ! [X3: A] :
          ( ~ ( P @ X3 )
         => ? [Y: A] :
              ( ( ord_less @ nat @ ( V @ Y ) @ ( V @ X3 ) )
              & ~ ( P @ Y ) ) )
     => ( P @ X ) ) )).

% infinite_descent_measure
thf(fact_43_mem__Collect__eq,axiom,(
    ! [A: $tType,A2: A,P: ( A > $o )] :
      ( ( member @ A @ A2 @ ( collect @ A @ P ) )
      = ( P @ A2 ) ) )).

% mem_Collect_eq
thf(fact_44_Collect__mem__eq,axiom,(
    ! [A: $tType,A3: ( set @ A )] :
      ( ( collect @ A
        @ ^ [X4: A] :
            ( member @ A @ X4 @ A3 ) )
      = A3 ) )).

% Collect_mem_eq
thf(fact_45_Collect__cong,axiom,(
    ! [A: $tType,P: ( A > $o ),Q: ( A > $o )] :
      ( ! [X3: A] :
          ( ( P @ X3 )
          = ( Q @ X3 ) )
     => ( ( collect @ A @ P )
        = ( collect @ A @ Q ) ) ) )).

% Collect_cong
thf(fact_46_ext,axiom,(
    ! [B: $tType,A: $tType,F: ( A > B ),G: ( A > B )] :
      ( ! [X3: A] :
          ( ( F @ X3 )
          = ( G @ X3 ) )
     => ( F = G ) ) )).

% ext
thf(fact_47_infinite__descent0__measure,axiom,(
    ! [A: $tType,V: ( A > nat ),P: ( A > $o ),X: A] :
      ( ! [X3: A] :
          ( ( ( V @ X3 )
            = ( zero_zero @ nat ) )
         => ( P @ X3 ) )
     => ( ! [X3: A] :
            ( ( ord_less @ nat @ ( zero_zero @ nat ) @ ( V @ X3 ) )
           => ( ~ ( P @ X3 )
             => ? [Y: A] :
                  ( ( ord_less @ nat @ ( V @ Y ) @ ( V @ X3 ) )
                  & ~ ( P @ Y ) ) ) )
       => ( P @ X ) ) ) )).

% infinite_descent0_measure
thf(fact_48_One__nat__def,axiom,
    ( ( one_one @ nat )
    = ( suc @ ( zero_zero @ nat ) ) )).

% One_nat_def
thf(fact_49_lift__Suc__mono__less__iff,axiom,(
    ! [A: $tType] :
      ( ( order @ A @ ( type2 @ A ) )
     => ! [F: ( nat > A ),N2: nat,M2: nat] :
          ( ! [N3: nat] :
              ( ord_less @ A @ ( F @ N3 ) @ ( F @ ( suc @ N3 ) ) )
         => ( ( ord_less @ A @ ( F @ N2 ) @ ( F @ M2 ) )
            = ( ord_less @ nat @ N2 @ M2 ) ) ) ) )).

% lift_Suc_mono_less_iff
thf(fact_50_lift__Suc__mono__less,axiom,(
    ! [A: $tType] :
      ( ( order @ A @ ( type2 @ A ) )
     => ! [F: ( nat > A ),N2: nat,N4: nat] :
          ( ! [N3: nat] :
              ( ord_less @ A @ ( F @ N3 ) @ ( F @ ( suc @ N3 ) ) )
         => ( ( ord_less @ nat @ N2 @ N4 )
           => ( ord_less @ A @ ( F @ N2 ) @ ( F @ N4 ) ) ) ) ) )).

% lift_Suc_mono_less
thf(fact_51_less__Suc__eq__0__disj,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ M2 @ ( suc @ N2 ) )
      = ( ( M2
          = ( zero_zero @ nat ) )
        | ? [J: nat] :
            ( ( M2
              = ( suc @ J ) )
            & ( ord_less @ nat @ J @ N2 ) ) ) ) )).

% less_Suc_eq_0_disj
thf(fact_52_gr0__implies__Suc,axiom,(
    ! [N2: nat] :
      ( ( ord_less @ nat @ ( zero_zero @ nat ) @ N2 )
     => ? [M: nat] :
          ( N2
          = ( suc @ M ) ) ) )).

% gr0_implies_Suc
thf(fact_53_gr0__conv__Suc,axiom,(
    ! [N2: nat] :
      ( ( ord_less @ nat @ ( zero_zero @ nat ) @ N2 )
      = ( ? [M4: nat] :
            ( N2
            = ( suc @ M4 ) ) ) ) )).

% gr0_conv_Suc
thf(fact_54_RuleSystem__Defs_Ocountable__R,axiom,(
    ! [Rule: $tType,Rules2: ( stream @ Rule )] :
      ( countable_countable @ Rule @ ( sset @ Rule @ Rules2 ) ) )).

% RuleSystem_Defs.countable_R
thf(fact_55_RuleSystem__Defs_ONE__R,axiom,(
    ! [Rule: $tType,Rules2: ( stream @ Rule )] :
      ( ( sset @ Rule @ Rules2 )
     != ( bot_bot @ ( set @ Rule ) ) ) )).

% RuleSystem_Defs.NE_R
thf(fact_56_not__less__less__Suc__eq,axiom,(
    ! [N2: nat,M2: nat] :
      ( ~ ( ord_less @ nat @ N2 @ M2 )
     => ( ( ord_less @ nat @ N2 @ ( suc @ M2 ) )
        = ( N2 = M2 ) ) ) )).

% not_less_less_Suc_eq
thf(fact_57_strict__inc__induct,axiom,(
    ! [I: nat,J2: nat,P: ( nat > $o )] :
      ( ( ord_less @ nat @ I @ J2 )
     => ( ! [I2: nat] :
            ( ( J2
              = ( suc @ I2 ) )
           => ( P @ I2 ) )
       => ( ! [I2: nat] :
              ( ( ord_less @ nat @ I2 @ J2 )
             => ( ( P @ ( suc @ I2 ) )
               => ( P @ I2 ) ) )
         => ( P @ I ) ) ) ) )).

% strict_inc_induct
thf(fact_58_less__Suc__induct,axiom,(
    ! [I: nat,J2: nat,P: ( nat > nat > $o )] :
      ( ( ord_less @ nat @ I @ J2 )
     => ( ! [I2: nat] :
            ( P @ I2 @ ( suc @ I2 ) )
       => ( ! [I2: nat,J3: nat,K: nat] :
              ( ( ord_less @ nat @ I2 @ J3 )
             => ( ( ord_less @ nat @ J3 @ K )
               => ( ( P @ I2 @ J3 )
                 => ( ( P @ J3 @ K )
                   => ( P @ I2 @ K ) ) ) ) )
         => ( P @ I @ J2 ) ) ) ) )).

% less_Suc_induct
thf(fact_59_less__trans__Suc,axiom,(
    ! [I: nat,J2: nat,K2: nat] :
      ( ( ord_less @ nat @ I @ J2 )
     => ( ( ord_less @ nat @ J2 @ K2 )
       => ( ord_less @ nat @ ( suc @ I ) @ K2 ) ) ) )).

% less_trans_Suc
thf(fact_60_Suc__less__SucD,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ ( suc @ M2 ) @ ( suc @ N2 ) )
     => ( ord_less @ nat @ M2 @ N2 ) ) )).

% Suc_less_SucD
thf(fact_61_less__antisym,axiom,(
    ! [N2: nat,M2: nat] :
      ( ~ ( ord_less @ nat @ N2 @ M2 )
     => ( ( ord_less @ nat @ N2 @ ( suc @ M2 ) )
       => ( M2 = N2 ) ) ) )).

% less_antisym
thf(fact_62_Suc__less__eq2,axiom,(
    ! [N2: nat,M2: nat] :
      ( ( ord_less @ nat @ ( suc @ N2 ) @ M2 )
      = ( ? [M5: nat] :
            ( ( M2
              = ( suc @ M5 ) )
            & ( ord_less @ nat @ N2 @ M5 ) ) ) ) )).

% Suc_less_eq2
thf(fact_63_not__less__eq,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ~ ( ord_less @ nat @ M2 @ N2 ) )
      = ( ord_less @ nat @ N2 @ ( suc @ M2 ) ) ) )).

% not_less_eq
thf(fact_64_less__Suc__eq,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ M2 @ ( suc @ N2 ) )
      = ( ( ord_less @ nat @ M2 @ N2 )
        | ( M2 = N2 ) ) ) )).

% less_Suc_eq
thf(fact_65_less__SucI,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ M2 @ N2 )
     => ( ord_less @ nat @ M2 @ ( suc @ N2 ) ) ) )).

% less_SucI
thf(fact_66_less__SucE,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ M2 @ ( suc @ N2 ) )
     => ( ~ ( ord_less @ nat @ M2 @ N2 )
       => ( M2 = N2 ) ) ) )).

% less_SucE
thf(fact_67_Suc__lessI,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ M2 @ N2 )
     => ( ( ( suc @ M2 )
         != N2 )
       => ( ord_less @ nat @ ( suc @ M2 ) @ N2 ) ) ) )).

% Suc_lessI
thf(fact_68_Suc__lessE,axiom,(
    ! [I: nat,K2: nat] :
      ( ( ord_less @ nat @ ( suc @ I ) @ K2 )
     => ~ ( ! [J3: nat] :
              ( ( ord_less @ nat @ I @ J3 )
             => ( K2
               != ( suc @ J3 ) ) ) ) ) )).

% Suc_lessE
thf(fact_69_Suc__lessD,axiom,(
    ! [M2: nat,N2: nat] :
      ( ( ord_less @ nat @ ( suc @ M2 ) @ N2 )
     => ( ord_less @ nat @ M2 @ N2 ) ) )).

% Suc_lessD
thf(fact_70_lessE,axiom,(
    ! [I: nat,K2: nat] :
      ( ( ord_less @ nat @ I @ K2 )
     => ( ( K2
         != ( suc @ I ) )
       => ~ ( ! [J3: nat] :
                ( ( ord_less @ nat @ I @ J3 )
               => ( K2
                 != ( suc @ J3 ) ) ) ) ) ) )).

% lessE
thf(fact_71_not0__implies__Suc,axiom,(
    ! [N2: nat] :
      ( ( N2
       != ( zero_zero @ nat ) )
     => ? [M: nat] :
          ( N2
          = ( suc @ M ) ) ) )).

% not0_implies_Suc
thf(fact_72_old_Onat_Oinducts,axiom,(
    ! [P: ( nat > $o ),Nat: nat] :
      ( ( P @ ( zero_zero @ nat ) )
     => ( ! [Nat3: nat] :
            ( ( P @ Nat3 )
           => ( P @ ( suc @ Nat3 ) ) )
       => ( P @ Nat ) ) ) )).

% old.nat.inducts
thf(fact_73_old_Onat_Oexhaust,axiom,(
    ! [Y3: nat] :
      ( ( Y3
       != ( zero_zero @ nat ) )
     => ~ ( ! [Nat3: nat] :
              ( Y3
             != ( suc @ Nat3 ) ) ) ) )).

% old.nat.exhaust
thf(fact_74_Zero__not__Suc,axiom,(
    ! [M2: nat] :
      ( ( zero_zero @ nat )
     != ( suc @ M2 ) ) )).

% Zero_not_Suc
thf(fact_75_Zero__neq__Suc,axiom,(
    ! [M2: nat] :
      ( ( zero_zero @ nat )
     != ( suc @ M2 ) ) )).

% Zero_neq_Suc
thf(fact_76_Suc__neq__Zero,axiom,(
    ! [M2: nat] :
      ( ( suc @ M2 )
     != ( zero_zero @ nat ) ) )).

% Suc_neq_Zero
thf(fact_77_zero__induct,axiom,(
    ! [P: ( nat > $o ),K2: nat] :
      ( ( P @ K2 )
     => ( ! [N3: nat] :
            ( ( P @ ( suc @ N3 ) )
           => ( P @ N3 ) )
       => ( P @ ( zero_zero @ nat ) ) ) ) )).

% zero_induct
thf(fact_78_diff__induct,axiom,(
    ! [P: ( nat > nat > $o ),M2: nat,N2: nat] :
      ( ! [X3: nat] :
          ( P @ X3 @ ( zero_zero @ nat ) )
     => ( ! [Y4: nat] :
            ( P @ ( zero_zero @ nat ) @ ( suc @ Y4 ) )
       => ( ! [X3: nat,Y4: nat] :
              ( ( P @ X3 @ Y4 )
             => ( P @ ( suc @ X3 ) @ ( suc @ Y4 ) ) )
         => ( P @ M2 @ N2 ) ) ) ) )).

% diff_induct
thf(fact_79_nat__induct,axiom,(
    ! [P: ( nat > $o ),N2: nat] :
      ( ( P @ ( zero_zero @ nat ) )
     => ( ! [N3: nat] :
            ( ( P @ N3 )
           => ( P @ ( suc @ N3 ) ) )
       => ( P @ N2 ) ) ) )).

% nat_induct
thf(fact_80_nat_OdiscI,axiom,(
    ! [Nat: nat,X2: nat] :
      ( ( Nat
        = ( suc @ X2 ) )
     => ( Nat
       != ( zero_zero @ nat ) ) ) )).

% nat.discI
thf(fact_81_old_Onat_Odistinct_I1_J,axiom,(
    ! [Nat2: nat] :
      ( ( zero_zero @ nat )
     != ( suc @ Nat2 ) ) )).

% old.nat.distinct(1)
thf(fact_82_old_Onat_Odistinct_I2_J,axiom,(
    ! [Nat4: nat] :
      ( ( suc @ Nat4 )
     != ( zero_zero @ nat ) ) )).

% old.nat.distinct(2)
thf(fact_83_nat_Odistinct_I1_J,axiom,(
    ! [X2: nat] :
      ( ( zero_zero @ nat )
     != ( suc @ X2 ) ) )).

% nat.distinct(1)
thf(fact_84_snth__sset,axiom,(
    ! [A: $tType,S: ( stream @ A ),N2: nat] :
      ( member @ A @ ( snth @ A @ S @ N2 ) @ ( sset @ A @ S ) ) )).

% snth_sset
thf(fact_85_smap__alt,axiom,(
    ! [A: $tType,B: $tType,F: ( B > A ),S: ( stream @ B ),S3: ( stream @ A )] :
      ( ( ( smap @ B @ A @ F @ S )
        = S3 )
      = ( ! [N: nat] :
            ( ( F @ ( snth @ B @ S @ N ) )
            = ( snth @ A @ S3 @ N ) ) ) ) )).

% smap_alt
thf(fact_86_n__not__Suc__n,axiom,(
    ! [N2: nat] :
      ( N2
     != ( suc @ N2 ) ) )).

% n_not_Suc_n
thf(fact_87_Suc__inject,axiom,(
    ! [X: nat,Y3: nat] :
      ( ( ( suc @ X )
        = ( suc @ Y3 ) )
     => ( X = Y3 ) ) )).

% Suc_inject
thf(fact_88_stream_Omap__ident,axiom,(
    ! [A: $tType,T: ( stream @ A )] :
      ( ( smap @ A @ A
        @ ^ [X4: A] : X4
        @ T )
      = T ) )).

% stream.map_ident
thf(fact_89_stream__smap__nats,axiom,(
    ! [A: $tType,S: ( stream @ A )] :
      ( S
      = ( smap @ nat @ A @ ( snth @ A @ S ) @ ( siterate @ nat @ suc @ ( zero_zero @ nat ) ) ) ) )).

% stream_smap_nats
thf(fact_90_RuleSystem__Defs_Osset__fenum,axiom,(
    ! [Rule: $tType,Rules2: ( stream @ Rule )] :
      ( ( sset @ Rule @ ( abstra1774373515_fenum @ Rule @ Rules2 ) )
      = ( sset @ Rule @ Rules2 ) ) )).

% RuleSystem_Defs.sset_fenum
thf(fact_91_countable__empty,axiom,(
    ! [A: $tType] :
      ( countable_countable @ A @ ( bot_bot @ ( set @ A ) ) ) )).

% countable_empty
thf(fact_92_bex__empty,axiom,(
    ! [A: $tType,P: ( A > $o )] :
      ~ ( ? [X5: A] :
            ( ( member @ A @ X5 @ ( bot_bot @ ( set @ A ) ) )
            & ( P @ X5 ) ) ) )).

% bex_empty
thf(fact_93_not__gr__zero,axiom,(
    ! [A: $tType] :
      ( ( canoni770627133id_add @ A @ ( type2 @ A ) )
     => ! [N2: A] :
          ( ( ~ ( ord_less @ A @ ( zero_zero @ A ) @ N2 ) )
          = ( N2
            = ( zero_zero @ A ) ) ) ) )).

% not_gr_zero
thf(fact_94_less__numeral__extra_I2_J,axiom,(
    ! [A: $tType] :
      ( ( linordered_semidom @ A @ ( type2 @ A ) )
     => ~ ( ord_less @ A @ ( one_one @ A ) @ ( zero_zero @ A ) ) ) )).

% less_numeral_extra(2)
thf(fact_95_less__numeral__extra_I1_J,axiom,(
    ! [A: $tType] :
      ( ( linordered_semidom @ A @ ( type2 @ A ) )
     => ( ord_less @ A @ ( zero_zero @ A ) @ ( one_one @ A ) ) ) )).

% less_numeral_extra(1)
thf(fact_96_zero__less__one,axiom,(
    ! [A: $tType] :
      ( ( zero_less_one @ A @ ( type2 @ A ) )
     => ( ord_less @ A @ ( zero_zero @ A ) @ ( one_one @ A ) ) ) )).

% zero_less_one
thf(fact_97_not__one__less__zero,axiom,(
    ! [A: $tType] :
      ( ( linord1659791738miring @ A @ ( type2 @ A ) )
     => ~ ( ord_less @ A @ ( one_one @ A ) @ ( zero_zero @ A ) ) ) )).

% not_one_less_zero
thf(fact_98_countableI__type,axiom,(
    ! [A: $tType] :
      ( ( countable @ A @ ( type2 @ A ) )
     => ! [A3: ( set @ A )] :
          ( countable_countable @ A @ A3 ) ) )).

% countableI_type
thf(fact_99_empty__iff,axiom,(
    ! [A: $tType,C: A] :
      ~ ( member @ A @ C @ ( bot_bot @ ( set @ A ) ) ) )).

% empty_iff
thf(fact_100_all__not__in__conv,axiom,(
    ! [A: $tType,A3: ( set @ A )] :
      ( ( ! [X4: A] :
            ~ ( member @ A @ X4 @ A3 ) )
      = ( A3
        = ( bot_bot @ ( set @ A ) ) ) ) )).

% all_not_in_conv
thf(fact_101_empty__Collect__eq,axiom,(
    ! [A: $tType,P: ( A > $o )] :
      ( ( ( bot_bot @ ( set @ A ) )
        = ( collect @ A @ P ) )
      = ( ! [X4: A] :
            ~ ( P @ X4 ) ) ) )).

% empty_Collect_eq
thf(fact_102_Collect__empty__eq,axiom,(
    ! [A: $tType,P: ( A > $o )] :
      ( ( ( collect @ A @ P )
        = ( bot_bot @ ( set @ A ) ) )
      = ( ! [X4: A] :
            ~ ( P @ X4 ) ) ) )).

% Collect_empty_eq
thf(fact_103_not__psubset__empty,axiom,(
    ! [A: $tType,A3: ( set @ A )] :
      ~ ( ord_less @ ( set @ A ) @ A3 @ ( bot_bot @ ( set @ A ) ) ) )).

% not_psubset_empty
thf(fact_104_zero__reorient,axiom,(
    ! [A: $tType] :
      ( ( zero @ A @ ( type2 @ A ) )
     => ! [X: A] :
          ( ( ( zero_zero @ A )
            = X )
          = ( X
            = ( zero_zero @ A ) ) ) ) )).

% zero_reorient
thf(fact_105_linorder__neqE__linordered__idom,axiom,(
    ! [A: $tType] :
      ( ( linordered_idom @ A @ ( type2 @ A ) )
     => ! [X: A,Y3: A] :
          ( ( X != Y3 )
         => ( ~ ( ord_less @ A @ X @ Y3 )
           => ( ord_less @ A @ Y3 @ X ) ) ) ) )).

% linorder_neqE_linordered_idom
thf(fact_106_one__reorient,axiom,(
    ! [A: $tType] :
      ( ( one @ A @ ( type2 @ A ) )
     => ! [X: A] :
          ( ( ( one_one @ A )
            = X )
          = ( X
            = ( one_one @ A ) ) ) ) )).

% one_reorient
thf(fact_107_ex__in__conv,axiom,(
    ! [A: $tType,A3: ( set @ A )] :
      ( ( ? [X4: A] :
            ( member @ A @ X4 @ A3 ) )
      = ( A3
       != ( bot_bot @ ( set @ A ) ) ) ) )).

% ex_in_conv
thf(fact_108_equals0I,axiom,(
    ! [A: $tType,A3: ( set @ A )] :
      ( ! [Y4: A] :
          ~ ( member @ A @ Y4 @ A3 )
     => ( A3
        = ( bot_bot @ ( set @ A ) ) ) ) )).

